src/AppBundle/Entity/Evaluation.php
<?php

namespace AppBundle\Entity;

use AppBundle\Form\EvaluationType;
use AppBundle\ValueObject\Rating;
use Doctrine\ORM\Mapping as ORM;

/**
 * Evaluation
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AppBundle\Entity\EvaluationRepository")
 */
class Evaluation
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var guid
     *
     * @ORM\Column(name="uuid", type="guid")
     */
    private $uuid;

    /**
     * @var string
     *
     * @ORM\Column(name="farm_name", type="string", length=255)
     */
    private $farmName;

    /**
     * @var string
     *
     * @ORM\Column(name="farm_category", type="string", length=255)
     */
    private $farmCategory;

    /**
     * @var float
     *
     * @ORM\Column(name="farm_position_latitude", type="float")
     */
    private $farmPositionLatitude;

    /**
     * @var float
     *
     * @ORM\Column(name="farm_position_longitude", type="float")
     */
    private $farmPositionLongitude;

    /**
     * @var string
     *
     * @ORM\Column(name="farm_website_url", type="string", length=255, nullable=true)
     */
    private $farmWebsiteUrl;

    /**
     * @var string
     *
     * @ORM\Column(name="farm_photo_url", type="string", length=255)
     */
    private $farmPhotoUrl;

    /**
     * @var integer
     *
     * @ORM\Column(name="rating_environment", type="integer")
     */
    private $ratingEnvironment;

    /**
     * @var integer
     *
     * @ORM\Column(name="rating_health", type="integer")
     */
    private $ratingHealth;

    /**
     * @var integer
     *
     * @ORM\Column(name="rating_social", type="integer")
     */
    private $ratingSocial;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set uuid
     *
     * @param guid $uuid
     *
     * @return Evaluation
     */
    public function setUuid($uuid)
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Get uuid
     *
     * @return guid
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Set farmName
     *
     * @param string $farmName
     *
     * @return Evaluation
     */
    public function setFarmName($farmName)
    {
        $this->farmName = $farmName;

        return $this;
    }

    /**
     * Get farmName
     *
     * @return string
     */
    public function getFarmName()
    {
        return $this->farmName;
    }

    /**
     * Set farmCategory
     *
     * @param string $farmCategory
     *
     * @return Evaluation
     */
    public function setFarmCategory($farmCategory)
    {
        $this->farmCategory = $farmCategory;

        return $this;
    }

    /**
     * Get farmCategory
     *
     * @return string
     */
    public function getFarmCategory()
    {
        return $this->farmCategory;
    }

    public function getFarmCategoryName()
    {
        return EvaluationType::$categories[$this->farmCategory];
    }

    /**
     * Set farmPositionLatitude
     *
     * @param float $farmPositionLatitude
     *
     * @return Evaluation
     */
    public function setFarmPositionLatitude($farmPositionLatitude)
    {
        $this->farmPositionLatitude = $farmPositionLatitude;

        return $this;
    }

    /**
     * Get farmPositionLatitude
     *
     * @return float
     */
    public function getFarmPositionLatitude()
    {
        return $this->farmPositionLatitude;
    }

    /**
     * Set farmPositionLongitude
     *
     * @param float $farmPositionLongitude
     *
     * @return Evaluation
     */
    public function setFarmPositionLongitude($farmPositionLongitude)
    {
        $this->farmPositionLongitude = $farmPositionLongitude;

        return $this;
    }

    /**
     * Get farmPositionLongitude
     *
     * @return float
     */
    public function getFarmPositionLongitude()
    {
        return $this->farmPositionLongitude;
    }

    /**
     * Set farmWebsiteUrl
     *
     * @param string $url
     *
     * @return Evaluation
     */
    public function setFarmWebsiteUrl($url)
    {
        $this->farmWebsiteUrl = $url;

        return $this;
    }

    /**
     * Get farmPhotoUrl
     *
     * @return string
     */
    public function getFarmWebsiteUrl()
    {
        return $this->farmWebsiteUrl;
    }

    /**
     * Set farmPhotoUrl
     *
     * @param string $url
     *
     * @return Evaluation
     */
    public function setFarmPhotoUrl($url)
    {
        $this->farmPhotoUrl = $url;

        return $this;
    }

    /**
     * Get farmPhotoUrl
     *
     * @return string
     */
    public function getFarmPhotoUrl()
    {
        return $this->farmPhotoUrl;
    }

    public function getRating()
    {
        return new Rating($this->ratingEnvironment, $this->ratingSocial, $this->ratingHealth);
    }

    /**
     * Set ratingEnvironment
     *
     * @param integer $ratingEnvironment
     *
     * @return Evaluation
     */
    public function setRatingEnvironment($ratingEnvironment)
    {
        $this->ratingEnvironment = $ratingEnvironment;

        return $this;
    }

    /**
     * Get ratingEnvironment
     *
     * @return integer
     */
    public function getRatingEnvironment()
    {
        return $this->ratingEnvironment;
    }

    /**
     * Set ratingHealth
     *
     * @param integer $ratingHealth
     *
     * @return Evaluation
     */
    public function setRatingHealth($ratingHealth)
    {
        $this->ratingHealth = $ratingHealth;

        return $this;
    }

    /**
     * Get ratingHealth
     *
     * @return integer
     */
    public function getRatingHealth()
    {
        return $this->ratingHealth;
    }

    /**
     * Set ratingSocial
     *
     * @param integer $ratingSocial
     *
     * @return Evaluation
     */
    public function setRatingSocial($ratingSocial)
    {
        $this->ratingSocial = $ratingSocial;

        return $this;
    }

    /**
     * Get ratingSocial
     *
     * @return integer
     */
    public function getRatingSocial()
    {
        return $this->ratingSocial;
    }
}

src/AppBundle/Form/EvaluationType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvaluationType extends AbstractType
{
    public static $categories = array(
        'cerealier' => "Céréalier",
        'eleveur' => "Éleveur",
        'maraicher' => "Maraîcher",
    );

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('uuid')
            ->add('farmName', 'text', array(
                'label' => "Nom de l'exploitation",
            ))
            ->add('farmCategory', 'choice', array(
                'label' => "Catégorie",
                'choices' => self::$categories,
            ))
            ->add('farmPositionLatitude', 'text', array('label' => "Latitude"))
            ->add('farmPositionLongitude', 'text', array('label' => "Longitude"))
            ->add('farmWebsiteUrl', 'text', array('label' => "Site web de l'exploitation"))
            ->add('farmPhotoUrl', 'text', array('label' => "Photo de l'exploitation"))
            ->add('ratingEnvironment', 'integer', array('label' => "Note Environnement"))
            ->add('ratingHealth', 'integer', array('label' => "Note Santé"))
            ->add('ratingSocial', 'integer', array('label' => "Note Social"))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Evaluation'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'appbundle_evaluation';
    }
}

src/AppBundle/Controller/EvaluationController.php
<?php

namespace AppBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use AppBundle\Entity\Evaluation;
use AppBundle\Form\EvaluationType;

/**
 * Evaluation controller.
 *
 * @Route("/admin/evaluation")
 */
class EvaluationController extends Controller
{

    /**
     * Lists all Evaluation entities.
     *
     * @Route("/", name="admin_evaluation")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('AppBundle:Evaluation')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Evaluation entity.
     *
     * @Route("/", name="admin_evaluation_create")
     * @Method("POST")
     * @Template("AppBundle:Evaluation:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Evaluation();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('admin_evaluation_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Evaluation entity.
     *
     * @param Evaluation $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Evaluation $entity)
    {
        $form = $this->createForm(new EvaluationType(), $entity, array(
            'action' => $this->generateUrl('admin_evaluation_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Enregistrer'));

        return $form;
    }

    /**
     * Displays a form to create a new Evaluation entity.
     *
     * @Route("/new", name="admin_evaluation_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Evaluation();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Evaluation entity.
     *
     * @Route("/{id}", name="admin_evaluation_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Evaluation')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Evaluation entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Evaluation entity.
     *
     * @Route("/{id}/edit", name="admin_evaluation_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Evaluation')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Evaluation entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Evaluation entity.
    *
    * @param Evaluation $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Evaluation $entity)
    {
        $form = $this->createForm(new EvaluationType(), $entity, array(
            'action' => $this->generateUrl('admin_evaluation_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Enregistrer'));

        return $form;
    }
    /**
     * Edits an existing Evaluation entity.
     *
     * @Route("/{id}", name="admin_evaluation_update")
     * @Method("PUT")
     * @Template("AppBundle:Evaluation:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('AppBundle:Evaluation')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Evaluation entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('admin_evaluation_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Evaluation entity.
     *
     * @Route("/{id}", name="admin_evaluation_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AppBundle:Evaluation')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Evaluation entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('admin_evaluation'));
    }

    /**
     * Creates a form to delete a Evaluation entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('admin_evaluation_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Supprimer'))
            ->getForm()
        ;
    }
}

src/AppBundle/Resources/views/Evaluation/edit.html.twig
{% extends '::base_admin.html.twig' %}

{% block body -%}
    <h1>Modifier une évaluation</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_evaluation') }}">
            Revenir à la liste
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Evaluation/index.html.twig
{% extends '::base_admin.html.twig' %}

{% block body -%}
    <h1>Liste des évaluations</h1>

    <table class="records_list table">
        <thead>
            <tr>
                <th>Exploitation</th>
                <th>Type</th>
                <th>Note environnement</th>
                <th>Note santé</th>
                <th>Note social</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entity in entities %}
            <tr>
                <td>{{ entity.farmName }}</td>
                <td>{{ entity.farmCategory }}</td>
                <td>{{ entity.ratingEnvironment }}</td>
                <td>{{ entity.ratingHealth }}</td>
                <td>{{ entity.ratingSocial }}</td>
                <td>
                <ul>
                    <li>
                        <a href="{{ path('admin_evaluation_show', { 'id': entity.id }) }}">voir</a>
                    </li>
                    <li>
                        <a href="{{ path('admin_evaluation_edit', { 'id': entity.id }) }}">éditer</a>
                    </li>
                </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <ul>
        <li>
            <a href="{{ path('admin_evaluation_new') }}">
                Renseigner une nouvelle évaluation
            </a>
        </li>
    </ul>
    {% endblock %}

src/AppBundle/Resources/views/Evaluation/new.html.twig
{% extends '::base_admin.html.twig' %}

{% block body -%}
    <h1>Renseigner une évaluation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_evaluation') }}">
            Revenir à la liste
        </a>
    </li>
</ul>
{% endblock %}

src/AppBundle/Resources/views/Evaluation/show.html.twig
{% extends '::base_admin.html.twig' %}

{% block body -%}
    <h1>Évaluation</h1>

    <div class="row">
        <div class="col-md-8">
            <table class="record_properties table">
                <tbody>
                    <tr>
                        <th>Nom de l'exploitation</th>
                        <td>{{ entity.farmName }}</td>
                    </tr>
                    <tr>
                        <th>Catégorie</th>
                        <td>{{ entity.farmCategoryName }}</td>
                    </tr>
                    <tr>
                        <th>Note Environnement</th>
                        <td>{{ entity.ratingEnvironment }}</td>
                    </tr>
                    <tr>
                        <th>Note Santé</th>
                        <td>{{ entity.ratingHealth }}</td>
                    </tr>
                    <tr>
                        <th>Note Social</th>
                        <td>{{ entity.ratingSocial }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <img src="https://maps.googleapis.com/maps/api/staticmap?{{
                [
                    'size=300x200',
                    'zoom=8',
                    'center=' ~ entity.farmPositionLatitude ~ ',' ~ entity.farmPositionLongitude,
                    'key=' ~ google_api_key,
                    'markers=|' ~ entity.farmPositionLatitude ~ ',' ~ entity.farmPositionLongitude
                ]|join('&')
            }}" />
        </div>
    </div>
    <div>
        <ul class="record_actions">
    <li>
        <a href="{{ path('admin_evaluation') }}">
            Retour à la liste
        </a>
    </li>
    <li>
        <a href="{{ path('admin_evaluation_edit', { 'id': entity.id }) }}">
            Modifier
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}